export const SIMPLIFY_ARITHMETIC__TEST = 'SIMPLIFY_ARITHMETIC__TEST';
export const SIMPLIFY_ARITHMETIC = 'SIMPLIFY_ARITHMETIC';
export const SIMPLIFY_ARITHMETIC__ADD = 'SIMPLIFY_ARITHMETIC__ADD';
export const SIMPLIFY_ARITHMETIC__SUBTRACT = 'SIMPLIFY_ARITHMETIC__SUBTRACT';
export const SIMPLIFY_ARITHMETIC__MULTIPLY = 'SIMPLIFY_ARITHMETIC__MULTIPLY';
export const SIMPLIFY_ARITHMETIC__POWER = 'SIMPLIFY_ARITHMETIC__POWER';
export const DIVISION_BY_NEGATIVE_ONE = 'DIVISION_BY_NEGATIVE_ONE';
export const DIVISION_BY_ONE = 'DIVISION_BY_ONE';
export const MULTIPLY_BY_ZERO = 'MULTIPLY_BY_ZERO';
export const REARRANGE_COEFF = 'REARRANGE_COEFF';
export const REDUCE_EXPONENT_BY_ZERO = 'REDUCE_EXPONENT_BY_ZERO';
export const REDUCE_ZERO_NUMERATOR = 'REDUCE_ZERO_NUMERATOR';
export const REMOVE_ADDING_ZERO = 'REMOVE_ADDING_ZERO';
export const REMOVE_EXPONENT_BY_ONE = 'REMOVE_EXPONENT_BY_ONE';
export const REMOVE_EXPONENT_BASE_ONE = 'REMOVE_EXPONENT_BASE_ONE';
export const REMOVE_EXPONENT_BASE_ZERO = 'REMOVE_EXPONENT_BASE_ZERO';
export const REMOVE_MULTIPLYING_BY_NEGATIVE_ONE = 'REMOVE_MULTIPLYING_BY_NEGATIVE_ONE';
export const REMOVE_MULTIPLYING_BY_ONE = 'REMOVE_MULTIPLYING_BY_ONE';
export const RESOLVE_DOUBLE_MINUS = 'RESOLVE_DOUBLE_MINUS';
export const COLLECT_AND_COMBINE_LIKE_TERMS = 'COLLECT_AND_COMBINE_LIKE_TERMS';
export const BREAK_UP_FRACTION = 'BREAK_UP_FRACTION';
export const CANCEL_MINUSES = 'CANCEL_MINUSES';
export const CANCEL_TERMS = 'CANCEL_TERMS';
export const SIMPLIFY_FRACTION = 'SIMPLIFY_FRACTION';
export const SIMPLIFY_SIGNS = 'SIMPLIFY_SIGNS';
export const ADD_FRACTIONS = 'ADD_FRACTIONS';
export const COMMON_DENOMINATOR = 'COMMON_DENOMINATOR';
export const MULTIPLY_FRACTIONS = 'MULTIPLY_FRACTIONS';
export const DISTRIBUTE_NEGATIVE_ONE = 'DISTRIBUTE_NEGATIVE_ONE';
export const ABSOLUTE_VALUE = 'ABSOLUTE_VALUE';
export const MULTIPLY_NTH_ROOTS = 'MULTIPLY_NTH_ROOTS';
export const KEMU_ORIGINAL_EXPRESSION = 'KEMU_ORIGINAL_EXPRESSION';
export const KEMU_MULTIPLY_SQRTS = 'KEMU_MULTIPLY_SQRTS';
export const KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT = 'KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT';
export const KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE = 'KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE';
export const KEMU_DIVIDE_POWERS_WITH_COMMON_BASE = 'KEMU_DIVIDE_POWERS_WITH_COMMON_BASE';
export const KEMU_CONVERT_ROOT_TO_POWER = 'KEMU_CONVERT_ROOT_TO_POWER';
export const KEMU_CONVERT_POWER_TO_ROOT = 'KEMU_CONVERT_POWER_TO_ROOT';
export const KEMU_POWER_FACTORS = 'KEMU_POWER_FACTORS';
export const KEMU_POWER_FRACTION = 'KEMU_POWER_FRACTION';
export const KEMU_POWER_SQRT = 'KEMU_POWER_SQRT';
export const KEMU_SQRT_FROM_ZERO = 'KEMU_SQRT_FROM_ZERO';
export const KEMU_SQRT_FROM_ONE = 'KEMU_SQRT_FROM_ONE';
export const KEMU_SQRT_FROM_POW = 'KEMU_SQRT_FROM_POW';
export const KEMU_SQRT_FROM_CONST = 'KEMU_SQRT_FROM_CONST';
export const KEMU_ROOT_FROM_CONST = 'KEMU_ROOT_FROM_CONST';
export const KEMU_ROOT_FROM_FRACTION = 'KEMU_ROOT_FROM_FRACTION';
export const KEMU_POWER_TO_MINUS_ONE = 'KEMU_POWER_TO_MINUS_ONE';
export const KEMU_POWER_TO_NEGATIVE_EXPONENT = 'KEMU_POWER_TO_NEGATIVE_EXPONENT';
export const KEMU_MULTIPLY_EXPONENTS = 'KEMU_MULTIPLY_EXPONENTS';
export const KEMU_REMOVE_UNNEDED_PARENTHESIS = 'KEMU_REMOVE_UNNEDED_PARENTHESIS';
export const KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR = 'KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR';
export const KEMU_REMOVE_DOUBLE_FRACTION = 'KEMU_REMOVE_DOUBLE_FRACTION';
export const KEMU_NUMERICAL_SQRT = 'KEMU_NUMERICAL_SQRT';
export const KEMU_NUMERICAL_DIV = 'KEMU_NUMERICAL_DIV';
export const KEMU_FACTOR_EXPRESSION_UNDER_ROOT = 'KEMU_FACTOR_EXPRESSION_UNDER_ROOT';
export const KEMU_DECIMAL_TO_FRACTION = 'KEMU_DECIMAL_TO_FRACTION';
export const KEMU_SHORT_MULTIPLICATION_AB2_ADD = 'KEMU_SHORT_MULTIPLICATION_AB2_ADD';
export const KEMU_SHORT_MULTIPLICATION_AB3_ADD = 'KEMU_SHORT_MULTIPLICATION_AB3_ADD';
export const KEMU_SHORT_MULTIPLICATION_ABN_ADD = 'KEMU_SHORT_MULTIPLICATION_ABN_ADD';
export const KEMU_SHORT_MULTIPLICATION_AB2_SUB = 'KEMU_SHORT_MULTIPLICATION_AB2_SUB';
export const KEMU_SHORT_MULTIPLICATION_AB3_SUB = 'KEMU_SHORT_MULTIPLICATION_AB3_SUB';
export const KEMU_SHORT_MULTIPLICATION_ABN_SUB = 'KEMU_SHORT_MULTIPLICATION_ABN_SUB';
export const KEMU_FUNCTION_VALUE = 'KEMU_FUNCTION_VALUE';
export const KEMU_PYTHAGOREAN_IDENTITY = 'KEMU_PYTHAGOREAN_IDENTITY';
export const KEMU_EVEN_FUNCTION_OF_NEGATIVE = 'KEMU_EVEN_FUNCTION_OF_NEGATIVE';
export const KEMU_ODD_FUNCTION_OF_NEGATIVE = 'KEMU_ODD_FUNCTION_OF_NEGATIVE';
export const KEMU_CONVERT_SIN_PER_COS_TO_TAN = 'KEMU_CONVERT_SIN_PER_COS_TO_TAN';
export const KEMU_CONVERT_COS_PER_SIN_TO_COT = 'KEMU_CONVERT_COS_PER_SIN_TO_COT';
export const KEMU_CANCEL_INVERSE_FUNCTION = 'KEMU_CANCEL_INVERSE_FUNCTION';
export const KEMU_DISTRIBUTE_MUL_OVER_ADD = 'KEMU_DISTRIBUTE_MUL_OVER_ADD';
export const PERCENTS_ADD = 'PERCENTS_ADD';
export const PERCENTS_SUB = 'PERCENTS_SUB';
export const PERCENTS_CONVERT_TO_FRACTION = 'PERCENTS_CONVERT_TO_FRACTION';
export const KEMU_LOG_XY_FROM_ONE = 'KEMU_LOG_XY_FROM_ONE';
export const KEMU_LOG_XY_FROM_BASE = 'KEMU_LOG_XY_FROM_BASE';
export const KEMU_LOG_XY_FROM_POWER = 'KEMU_LOG_XY_FROM_POWER';
export default {
    SIMPLIFY_ARITHMETIC__TEST,
    SIMPLIFY_ARITHMETIC,
    SIMPLIFY_ARITHMETIC__ADD,
    SIMPLIFY_ARITHMETIC__SUBTRACT,
    SIMPLIFY_ARITHMETIC__MULTIPLY,
    SIMPLIFY_ARITHMETIC__POWER,
    DIVISION_BY_NEGATIVE_ONE,
    DIVISION_BY_ONE,
    MULTIPLY_BY_ZERO,
    REARRANGE_COEFF,
    REDUCE_EXPONENT_BY_ZERO,
    REDUCE_ZERO_NUMERATOR,
    REMOVE_ADDING_ZERO,
    REMOVE_EXPONENT_BY_ONE,
    REMOVE_EXPONENT_BASE_ONE,
    REMOVE_EXPONENT_BASE_ZERO,
    REMOVE_MULTIPLYING_BY_NEGATIVE_ONE,
    REMOVE_MULTIPLYING_BY_ONE,
    RESOLVE_DOUBLE_MINUS,
    COLLECT_AND_COMBINE_LIKE_TERMS,
    BREAK_UP_FRACTION,
    CANCEL_MINUSES,
    CANCEL_TERMS,
    SIMPLIFY_FRACTION,
    SIMPLIFY_SIGNS,
    ADD_FRACTIONS,
    COMMON_DENOMINATOR,
    MULTIPLY_FRACTIONS,
    DISTRIBUTE_NEGATIVE_ONE,
    ABSOLUTE_VALUE,
    MULTIPLY_NTH_ROOTS,
    KEMU_ORIGINAL_EXPRESSION,
    KEMU_MULTIPLY_SQRTS,
    KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT,
    KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE,
    KEMU_DIVIDE_POWERS_WITH_COMMON_BASE,
    KEMU_CONVERT_ROOT_TO_POWER,
    KEMU_CONVERT_POWER_TO_ROOT,
    KEMU_POWER_FACTORS,
    KEMU_POWER_FRACTION,
    KEMU_POWER_SQRT,
    KEMU_SQRT_FROM_ZERO,
    KEMU_SQRT_FROM_ONE,
    KEMU_SQRT_FROM_POW,
    KEMU_SQRT_FROM_CONST,
    KEMU_ROOT_FROM_CONST,
    KEMU_ROOT_FROM_FRACTION,
    KEMU_POWER_TO_MINUS_ONE,
    KEMU_POWER_TO_NEGATIVE_EXPONENT,
    KEMU_MULTIPLY_EXPONENTS,
    KEMU_REMOVE_UNNEDED_PARENTHESIS,
    KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR,
    KEMU_REMOVE_DOUBLE_FRACTION,
    KEMU_NUMERICAL_SQRT,
    KEMU_NUMERICAL_DIV,
    KEMU_FACTOR_EXPRESSION_UNDER_ROOT,
    KEMU_DECIMAL_TO_FRACTION,
    KEMU_SHORT_MULTIPLICATION_AB2_ADD,
    KEMU_SHORT_MULTIPLICATION_AB3_ADD,
    KEMU_SHORT_MULTIPLICATION_ABN_ADD,
    KEMU_SHORT_MULTIPLICATION_AB2_SUB,
    KEMU_SHORT_MULTIPLICATION_AB3_SUB,
    KEMU_SHORT_MULTIPLICATION_ABN_SUB,
    KEMU_FUNCTION_VALUE,
    KEMU_PYTHAGOREAN_IDENTITY,
    KEMU_EVEN_FUNCTION_OF_NEGATIVE,
    KEMU_ODD_FUNCTION_OF_NEGATIVE,
    KEMU_CONVERT_SIN_PER_COS_TO_TAN,
    KEMU_CONVERT_COS_PER_SIN_TO_COT,
    KEMU_CANCEL_INVERSE_FUNCTION,
    KEMU_DISTRIBUTE_MUL_OVER_ADD,
    PERCENTS_ADD,
    PERCENTS_SUB,
    PERCENTS_CONVERT_TO_FRACTION,
    KEMU_LOG_XY_FROM_ONE,
    KEMU_LOG_XY_FROM_BASE,
    KEMU_LOG_XY_FROM_POWER
};
