export const SIMPLIFY_ARITHMETIC = 'SIMPLIFY_ARITHMETIC' as const
export const SIMPLIFY_ARITHMETIC__ADD = 'SIMPLIFY_ARITHMETIC__ADD' as const
export const SIMPLIFY_ARITHMETIC__SUBTRACT = 'SIMPLIFY_ARITHMETIC__SUBTRACT' as const
export const SIMPLIFY_ARITHMETIC__MULTIPLY = 'SIMPLIFY_ARITHMETIC__MULTIPLY' as const
export const SIMPLIFY_ARITHMETIC__POWER = 'SIMPLIFY_ARITHMETIC__POWER' as const
export const DIVISION_BY_NEGATIVE_ONE = 'DIVISION_BY_NEGATIVE_ONE' as const
export const DIVISION_BY_ONE = 'DIVISION_BY_ONE' as const
export const MULTIPLY_BY_ZERO = 'MULTIPLY_BY_ZERO' as const
export const REARRANGE_COEFF = 'REARRANGE_COEFF' as const
export const REDUCE_EXPONENT_BY_ZERO = 'REDUCE_EXPONENT_BY_ZERO' as const
export const REDUCE_ZERO_NUMERATOR = 'REDUCE_ZERO_NUMERATOR' as const
export const REMOVE_ADDING_ZERO = 'REMOVE_ADDING_ZERO' as const
export const REMOVE_EXPONENT_BY_ONE = 'REMOVE_EXPONENT_BY_ONE' as const
export const REMOVE_EXPONENT_BASE_ONE = 'REMOVE_EXPONENT_BASE_ONE' as const
export const REMOVE_EXPONENT_BASE_ZERO = 'REMOVE_EXPONENT_BASE_ZERO' as const
export const REMOVE_MULTIPLYING_BY_NEGATIVE_ONE = 'REMOVE_MULTIPLYING_BY_NEGATIVE_ONE' as const
export const REMOVE_MULTIPLYING_BY_ONE = 'REMOVE_MULTIPLYING_BY_ONE' as const
export const RESOLVE_DOUBLE_MINUS = 'RESOLVE_DOUBLE_MINUS' as const
export const COLLECT_AND_COMBINE_LIKE_TERMS = 'COLLECT_AND_COMBINE_LIKE_TERMS' as const
export const BREAK_UP_FRACTION = 'BREAK_UP_FRACTION' as const
export const CANCEL_MINUSES = 'CANCEL_MINUSES' as const
export const CANCEL_TERMS = 'CANCEL_TERMS' as const
export const SIMPLIFY_FRACTION = 'SIMPLIFY_FRACTION' as const
export const SIMPLIFY_SIGNS = 'SIMPLIFY_SIGNS' as const
export const ADD_FRACTIONS = 'ADD_FRACTIONS' as const
export const COMMON_DENOMINATOR = 'COMMON_DENOMINATOR' as const
export const MULTIPLY_FRACTIONS = 'MULTIPLY_FRACTIONS' as const
export const DISTRIBUTE_NEGATIVE_ONE = 'DISTRIBUTE_NEGATIVE_ONE' as const
export const ABSOLUTE_VALUE = 'ABSOLUTE_VALUE' as const
export const MULTIPLY_NTH_ROOTS = 'MULTIPLY_NTH_ROOTS' as const
export const KEMU_ORIGINAL_EXPRESSION = 'KEMU_ORIGINAL_EXPRESSION' as const
export const KEMU_MULTIPLY_SQRTS = 'KEMU_MULTIPLY_SQRTS' as const
export const KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT = 'KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT' as const
export const KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE = 'KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE' as const
export const KEMU_DIVIDE_POWERS_WITH_COMMON_BASE = 'KEMU_DIVIDE_POWERS_WITH_COMMON_BASE' as const
export const KEMU_CONVERT_ROOT_TO_POWER = 'KEMU_CONVERT_ROOT_TO_POWER' as const
export const KEMU_CONVERT_POWER_TO_ROOT = 'KEMU_CONVERT_POWER_TO_ROOT' as const
export const KEMU_POWER_FACTORS = 'KEMU_POWER_FACTORS' as const
export const KEMU_POWER_FRACTION = 'KEMU_POWER_FRACTION' as const
export const KEMU_POWER_SQRT = 'KEMU_POWER_SQRT' as const
export const KEMU_SQRT_FROM_ZERO = 'KEMU_SQRT_FROM_ZERO' as const
export const KEMU_SQRT_FROM_ONE = 'KEMU_SQRT_FROM_ONE' as const
export const KEMU_SQRT_FROM_POW = 'KEMU_SQRT_FROM_POW' as const
export const KEMU_SQRT_FROM_CONST = 'KEMU_SQRT_FROM_CONST' as const
export const KEMU_ROOT_FROM_CONST = 'KEMU_ROOT_FROM_CONST' as const
export const KEMU_ROOT_FROM_FRACTION = 'KEMU_ROOT_FROM_FRACTION' as const
export const KEMU_POWER_TO_MINUS_ONE = 'KEMU_POWER_TO_MINUS_ONE' as const
export const KEMU_POWER_TO_NEGATIVE_EXPONENT = 'KEMU_POWER_TO_NEGATIVE_EXPONENT' as const
export const KEMU_MULTIPLY_EXPONENTS = 'KEMU_MULTIPLY_EXPONENTS' as const
export const KEMU_REMOVE_UNNEDED_PARENTHESIS = 'KEMU_REMOVE_UNNEDED_PARENTHESIS' as const
export const KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR = 'KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR' as const
export const KEMU_REMOVE_DOUBLE_FRACTION = 'KEMU_REMOVE_DOUBLE_FRACTION' as const
export const KEMU_NUMERICAL_SQRT = 'KEMU_NUMERICAL_SQRT' as const
export const KEMU_NUMERICAL_DIV = 'KEMU_NUMERICAL_DIV' as const
export const KEMU_FACTOR_EXPRESSION_UNDER_ROOT = 'KEMU_FACTOR_EXPRESSION_UNDER_ROOT' as const
export const KEMU_DECIMAL_TO_FRACTION = 'KEMU_DECIMAL_TO_FRACTION' as const
export const KEMU_SHORT_MULTIPLICATION_AB2_ADD = 'KEMU_SHORT_MULTIPLICATION_AB2_ADD' as const
export const KEMU_SHORT_MULTIPLICATION_AB3_ADD = 'KEMU_SHORT_MULTIPLICATION_AB3_ADD' as const
export const KEMU_SHORT_MULTIPLICATION_ABN_ADD = 'KEMU_SHORT_MULTIPLICATION_ABN_ADD' as const
export const KEMU_SHORT_MULTIPLICATION_AB2_SUB = 'KEMU_SHORT_MULTIPLICATION_AB2_SUB' as const
export const KEMU_SHORT_MULTIPLICATION_AB3_SUB = 'KEMU_SHORT_MULTIPLICATION_AB3_SUB' as const
export const KEMU_SHORT_MULTIPLICATION_ABN_SUB = 'KEMU_SHORT_MULTIPLICATION_ABN_SUB' as const
export const KEMU_FUNCTION_VALUE = 'KEMU_FUNCTION_VALUE' as const
export const KEMU_PYTHAGOREAN_IDENTITY = 'KEMU_PYTHAGOREAN_IDENTITY' as const
export const KEMU_EVEN_FUNCTION_OF_NEGATIVE = 'KEMU_EVEN_FUNCTION_OF_NEGATIVE' as const
export const KEMU_ODD_FUNCTION_OF_NEGATIVE = 'KEMU_ODD_FUNCTION_OF_NEGATIVE' as const
export const KEMU_CONVERT_SIN_PER_COS_TO_TAN = 'KEMU_CONVERT_SIN_PER_COS_TO_TAN' as const
export const KEMU_CONVERT_COS_PER_SIN_TO_COT = 'KEMU_CONVERT_COS_PER_SIN_TO_COT' as const
export const KEMU_CANCEL_INVERSE_FUNCTION = 'KEMU_CANCEL_INVERSE_FUNCTION' as const
export const KEMU_DISTRIBUTE_MUL_OVER_ADD = 'KEMU_DISTRIBUTE_MUL_OVER_ADD' as const
export const PERCENTS_ADD = 'PERCENTS_ADD' as const
export const PERCENTS_SUB = 'PERCENTS_SUB' as const
export const PERCENTS_CONVERT_TO_FRACTION = 'PERCENTS_CONVERT_TO_FRACTION' as const
export const KEMU_LOG_XY_FROM_ONE = 'KEMU_LOG_XY_FROM_ONE' as const
export const KEMU_LOG_XY_FROM_BASE = 'KEMU_LOG_XY_FROM_BASE' as const
export const KEMU_LOG_XY_FROM_POWER = 'KEMU_LOG_XY_FROM_POWER' as const

export const SimplifyArithmetic = {
  SIMPLIFY_ARITHMETIC,
  SIMPLIFY_ARITHMETIC__ADD,
  SIMPLIFY_ARITHMETIC__SUBTRACT,
  SIMPLIFY_ARITHMETIC__MULTIPLY,
  SIMPLIFY_ARITHMETIC__POWER,
  KEMU_DISTRIBUTE_MUL_OVER_ADD,
} as const

export const DivisionRules = {
  DIVISION_BY_NEGATIVE_ONE,
  DIVISION_BY_ONE,
  KEMU_DIVIDE_POWERS_WITH_COMMON_BASE,
  KEMU_REMOVE_DOUBLE_FRACTION,
} as const

export const MultiplicationRules = {
  SIMPLIFY_ARITHMETIC__MULTIPLY, // Also in SimplifyArithmetic
  MULTIPLY_BY_ZERO,
  MULTIPLY_FRACTIONS,
  MULTIPLY_NTH_ROOTS,
  DISTRIBUTE_NEGATIVE_ONE,
  KEMU_MULTIPLY_SQRTS,
  KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT,
  KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE,
  KEMU_MULTIPLY_EXPONENTS,

  // Multiply Short Formulas
  KEMU_SHORT_MULTIPLICATION_AB2_ADD,
  KEMU_SHORT_MULTIPLICATION_AB3_ADD,
  KEMU_SHORT_MULTIPLICATION_ABN_ADD,
  KEMU_SHORT_MULTIPLICATION_AB2_SUB,
  KEMU_SHORT_MULTIPLICATION_AB3_SUB,
  KEMU_SHORT_MULTIPLICATION_ABN_SUB,
} as const

export const CoefficientSimplificationRules = {
  REARRANGE_COEFF,
  CANCEL_MINUSES,
  CANCEL_TERMS,
  KEMU_FACTOR_EXPRESSION_UNDER_ROOT,
} as const

export const ExponentSimplificationRules = {
  REDUCE_EXPONENT_BY_ZERO,
  REMOVE_EXPONENT_BY_ONE,
  REMOVE_EXPONENT_BASE_ONE,
  REMOVE_EXPONENT_BASE_ZERO,
  KEMU_POWER_FACTORS,
  KEMU_POWER_TO_MINUS_ONE,
  KEMU_POWER_TO_NEGATIVE_EXPONENT,
} as const

export const ExpressionSimplificationRules = {
  REMOVE_ADDING_ZERO,
  REMOVE_MULTIPLYING_BY_NEGATIVE_ONE,
  REMOVE_MULTIPLYING_BY_ONE,
  RESOLVE_DOUBLE_MINUS,
  SIMPLIFY_SIGNS,
  COLLECT_AND_COMBINE_LIKE_TERMS,
  KEMU_REMOVE_UNNEDED_PARENTHESIS,
  KEMU_ORIGINAL_EXPRESSION,
} as const

export const AbsoluteValueRules = {
  ABSOLUTE_VALUE,
} as const

export const FractionRules = {
  ADD_FRACTIONS,
  COMMON_DENOMINATOR,
  MULTIPLY_FRACTIONS,

  SIMPLIFY_FRACTION,
  KEMU_DECIMAL_TO_FRACTION,
  KEMU_ROOT_FROM_FRACTION,
  KEMU_REMOVE_FRACTION_WITH_UNIT_NUMERATOR,
  BREAK_UP_FRACTION,
  KEMU_REMOVE_DOUBLE_FRACTION, // Also in DivisionRules
} as const

export const TrigonometricRules = {
  KEMU_PYTHAGOREAN_IDENTITY,
  KEMU_EVEN_FUNCTION_OF_NEGATIVE,
  KEMU_ODD_FUNCTION_OF_NEGATIVE,
  KEMU_CONVERT_SIN_PER_COS_TO_TAN,
  KEMU_CONVERT_COS_PER_SIN_TO_COT,
  KEMU_CANCEL_INVERSE_FUNCTION,
  KEMU_FUNCTION_VALUE,
} as const

export const LogarithmRules = {
  KEMU_LOG_XY_FROM_ONE,
  KEMU_LOG_XY_FROM_BASE,
  KEMU_LOG_XY_FROM_POWER,
} as const

export const PercentageRules = {
  PERCENTS_ADD,
  PERCENTS_SUB,
  PERCENTS_CONVERT_TO_FRACTION,
} as const

export const RootAndPowerRules = {
  KEMU_MULTIPLY_SQRTS, // Also in MultiplicationRules
  KEMU_MULTIPLY_SQRTS_WITH_COMMON_ROOT, // Also in MultiplicationRules
  KEMU_MULTIPLY_POWERS_WITH_COMMON_BASE, // Also in MultiplicationRules
  KEMU_DIVIDE_POWERS_WITH_COMMON_BASE, // Also in DivisionRules
  KEMU_CONVERT_ROOT_TO_POWER,
  KEMU_CONVERT_POWER_TO_ROOT,
  KEMU_POWER_FACTORS, // Also in ExponentSimplificationRules
  KEMU_POWER_FRACTION,
  KEMU_POWER_SQRT,
  KEMU_SQRT_FROM_ZERO,
  KEMU_SQRT_FROM_ONE,
  KEMU_SQRT_FROM_POW,
  KEMU_SQRT_FROM_CONST,
  KEMU_ROOT_FROM_CONST,
  KEMU_ROOT_FROM_FRACTION, // Also in FractionRules
  KEMU_POWER_TO_MINUS_ONE, // Also in ExponentSimplificationRules
  KEMU_POWER_TO_NEGATIVE_EXPONENT, // Also in ExponentSimplificationRules
} as const

export default {
  ...SimplifyArithmetic,
  ...DivisionRules,
  ...MultiplicationRules,
  ...CoefficientSimplificationRules,
  ...ExponentSimplificationRules,
  ...ExpressionSimplificationRules,
  ...AbsoluteValueRules,
  ...FractionRules,
  ...TrigonometricRules,
  ...LogarithmRules,
  ...PercentageRules,
  ...RootAndPowerRules,
  // simplifyArithmetic: SimplifyArithmetic,
  // divisionRules: DivisionRules,
  // multiplicationRules: MultiplicationRules,
  // coefficientSimplificationRules: CoefficientSimplificationRules,
  // exponentSimplificationRules: ExponentSimplificationRules,
  // expressionSimplificationRules: ExpressionSimplificationRules,
  // absoluteValueRules: AbsoluteValueRules,
  // fractionRules: FractionRules,
  // trigonometricRules: TrigonometricRules,
  // logarithmRules: LogarithmRules,
  // percentageRules: PercentageRules,
  // rootAndPowerRules: RootAndPowerRules,
} as const
